### ISSUE TITLE
Generic Type to Hexadecimal String utility function

### ISSUE THREAD

**Issue by KarthikJay** [NGCP/xbeeplus#1]
Inside Utility.cpp:

Implement a generic Type to Hexadecimal String utility function.
The function should return a standard string with space formatted hexadecimal octets
Examples: FF A8 C6

In order to make it generic you might need to use a byte array to split up the data type, although there might be faster ways to do it.
Link here for example code:
http://www.cplusplus.com/forum/beginner/155821/

**Comment by MichaelWallace30** [comment]
Is boost just for serial connection? Also does this work on Windows too?

**Comment by KarthikJay** [comment]
Yea, boost is being used to handle the serial connections, and threading for us.

Right now the library isn't feature complete, nor has it been tested on windows.

I'll add it to a milestone so that you can see when that progress has been made.

**Comment by zhangh94** [comment]
This is resolved in pull request #7
