### ISSUE TITLE
XBee Interface doesnt always connect

### ISSUE THREAD

**Issue by zhangh94** [NGCP/xbeeplus#19]
SerialXBee class AyncRead...() function wont always read messages. About 1 in 3 times, the function will be called, but no Frames will be read. A restart of the Xbee and program will usually solve this.

**Comment by zhangh94** [comment]
XCTU seems to work to fix a connection issue. If a connection issue occurs (GCS cant open serial port), XCTU can be used to open/close the serial port for the radio, and the GCS will be work properly in the next run.

Maybe an issue with the serial port not closing properly in the Xbeeplus API?

**Comment by KarthikJay** [comment]
K I'll add a proper destructor to the class on Teusday.
I'll also add an issue to update the exceptions so they actually get thrown on errors,
