### ISSUE TITLE
Create ByteSum Utility Function

### ISSUE THREAD

**Issue by KarthikJay** [NGCP/xbeeplus#4]
Create a generic byte sum function with the following prototype:
uint8_t ByteSum(T item);
uint8_t ByteSum(std::string item);
uint8_t ByteSum(char *item)

The function should take in any integral type (
It should then sum the bytes (into a uin8_t), disregarding overflow.
This uint8_t is then returned.

Once implementation is tested, use it inside the SetChecksum() functions of each packet data type.

**Comment by KarthikJay** [comment]
https://isocpp.org/wiki/faq/templates#fn-templates-explicit-calls

**Comment by zhangh94** [comment]
This is resolved in pull request #7
